language: cpp
# Important: Travis sets the CC and CXX environment variables according to the compiler you select. https://docs.travis-ci.com/user/languages/cpp/#choosing-compilers-to-test-against

sudo: false

matrix:
  include:
# GCC versions for Xenial/Bionic are given here: https://docs.travis-ci.com/user/languages/cpp/#gcc-on-linux
# Likewise for Clang: https://docs.travis-ci.com/user/languages/cpp/#clang-on-linux
    - name: "GCC 5.4.0 on Xenial (16.04 LTS)"
      os: linux
      dist: xenial
      compiler: gcc
    - name: "Clang 7 on Xenial (16.04 LTS)"
      os: linux
      dist: xenial
      compiler: clang
    - name: "GCC 7.4.0 on Bionic (18.04 LTS)"
      os: linux
      dist: bionic
      compiler: gcc
    - name: "Clang 7 on Bionic (18.04 LTS)"
      os: linux
      dist: bionic
      compiler: clang
# For the mac builds, info about installing GCC is from here: https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos
# Likewise, info for clang is from here: https://docs.travis-ci.com/user/languages/cpp/#clang-on-macos
# Info for Python is from here: https://docs.brew.sh/Homebrew-and-Python
    - name: "GCC 5 on macOS 10.12"
      os: osx
      osx_image: xcode9.2
      addons:
        homebrew:
          packages:
            - gcc5
            - python
          update: true
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
# NOTE: The gcc5 build outputs lots of warnings like the ones in this SO question: https://stackoverflow.com/q/39865367
# An answerer says it's nothing to worry about.
    - name: "Clang on macOS 10.12"
      os: osx
      osx_image: xcode9.2
      compiler: clang
      addons:
        homebrew:
          packages:
            - python
          update: true
    - name: "GCC 7 on macOS 10.14"
      os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
            - gcc@7
          update: true
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: "Clang on macOS 10.14"
      os: osx
      osx_image: xcode11
      compiler: clang


before_install:
  - eval "${MATRIX_EVAL}"
  - echo "CC:" $CC
  - $CC --version
  - echo "CXX:" $CXX
  - $CXX --version
  - cmake --version
  - make --version
  - python3 --version

# For 'language: cpp' there is no install phase: https://docs.travis-ci.com/user/languages/cpp/#dependency-management
# That's fine because we've already taken care of dependencies above.

script:
  - mkdir debug
  - cd debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target all
  - ./runtest
  - python3 ../test/integration_tests.py escape
  - cd ..
  - mkdir release
  - cd release
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target all
  - ./runtest
  - python3 ../test/integration_tests.py escape
