version: 1.0.{build}

build:
  verbosity: minimal

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017


environment:
  matrix:
    - GENERATOR: ""Visual Studio 12 2013""
    - GENERATOR: ""Visual Studio 14 2015""
    - GENERATOR: ""Visual Studio 15 2017""

build_script:
  - mkdir build
  - cd build
  - cmake -G %GENERATOR% ..
  - cmake --build . --target runtest

before_test:
  - dir

test_script:
  - .\Debug\runtest.exe