version: 1.0.{build}

build:
  verbosity: minimal

# Instead of specifying image at the top level, we use the APPVEYOR_BUILD_WORKER_IMAGE
# environment variable: https://www.appveyor.com/docs/build-environment/#using-multiple-images-for-the-same-build
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      USING_JAVA: "yes"
      USING_HASKELL: "yes"

# The set PATH line is modified from here: https://github.com/appveyor/ci/issues/1426
install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\Java\jdk1.8.0\bin;%PATH%
  - ps: if ($env:USING_HASKELL -eq "yes") {choco install ghc --version=9.0.1} else {echo "Not installing Haskell."}

# Note: was having issues with cmd not properly passing the quoted variable
# to cmake, so I switched to powershell. Judging from googletest's appveyor.yml,
# it seems that this should work: https://github.com/google/googletest/blob/master/appveyor.yml
build_script:
  - ps: md build
  - ps: cd build
  - ps: cmake .. -G "$env:GENERATOR" -DCMAKE_CONFIGURATION_TYPES="Debug;Release"
  - ps: cmake --build . --config Debug
  - ps: cmake --build . --config Release

test_script:
  - ps: .\Debug\runtest.exe
  - ps: C:\Python35-x64\python.exe ..\test\integration_tests.py .\Debug\escape.exe
  - ps: .\Release\runtest.exe
  - ps: C:\Python35-x64\python.exe ..\test\integration_tests.py .\Release\escape.exe
  - ps: cd ..
  - ps: if ($env:USING_JAVA -eq "yes") {.\java\ci\win_ciscript.ps1} else {echo "Not running Java tests."}
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: if ($env:USING_HASKELL -eq "yes") {.\haskell\ci\win_ciscript.ps1} else {echo "Not running Haskell tests."}
# Preinstalled Python locations are listed here:
# https://www.appveyor.com/docs/windows-images-software/#python
