version: 1.0.{build}

build:
  verbosity: minimal

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017


environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
    - GENERATOR: "Visual Studio 14 2015"
    - GENERATOR: "Visual Studio 15 2017"

# Note: was having issues with cmd not properly passing the quoted variable
# to cmake, so I switched to powershell. Judging from googletest's appveyor.yml,
# it seems that this should work: https://github.com/google/googletest/blob/master/appveyor.yml
# -Vicram
build_script:
  - ps: md build
  - ps: cd build
  - ps: cmake -G "$env:GENERATOR" ..
  - ps: cmake --build . --target runtest

test_script:
  - ps: .\Debug\runtest.exe
